### ISSUE TITLE
Inserir o postgresql como opção de banco de dados no projeto

### ISSUE THREAD

**Issue by cadumsx** [spbgovbr/sei-docker#41]
O SEI 4 permite o uso do postgres como banco de dados, porem este projeto apresenta como opções apenas  oracle, mysql e sqlserver.

**Comment by marlinhares** [comment]
Olá @cadumsx 
Precisamos de uma base de referência do poder executivo em postgres, a exemplo da que temos para mysql, sqlserver e postgres.
Em breve teremos a base de referência para o sistema Super, talvez consigamos adaptar sem esforço para o SEI.

**Comment by marlinhares** [comment]
Já liberado e funcional

Duvidas avisar
