### ISSUE TITLE
Problema de permissão ao rodar o SEI

### ISSUE THREAD

**Issue by soldate** [spbgovbr/sei-docker#43]
Olá, tive um problema de permissão para rodar o SEI e resolvi colocando o 
&& chmod -R 755 /opt/ 
na linha abaixo, dentro do Makefile.

docker run --rm -v $(LOCALIZACAO_FONTES_SEI):/source -v $(VOLUME_FONTES):/opt -w /source alpine sh -c "cp -R infra sei sip /opt/ && chmod -R 755 /opt/"

**Comment by marlinhares** [comment]
Pode ser assim @soldate Apenas devemos tomar cuidado q quem está rodando esse chmod é o alpine como root.
