### ISSUE TITLE
erro em /opt/sei/config

### ISSUE THREAD

**Issue by wll8090** [spbgovbr/sei-docker#45]
creio que essa pasta estar vinculada ao volume 
logs retorna um erro:   "cp: cannot create regular file '/opt/sei/config/': Not a directory"  

ao entrar no container, a pasta /opt/  não tem os arquivos requeridos a seguir:
na linha 83 do arquivo:  containeres/app/files/scripts-e-automatizadores/entrypoint-atualizador.sh
e tbm 
na linha 81 do arquivo :  containeres/app/files/scripts-e-automatizadores/entrypoint.sh

algum erro não add os mesmos para a pasta.

**Comment by marlinhares** [comment]
Olá @wll8090 
Pelo que eu entendi vc deve ter subido o sistema sem antes posicionar corretamente os Fontes. Nesse caso pode acontecer esses problemas no mapeamento dos arquivos.
Tenha em mente q os fontes n fazem parte do ecossistema, portanto eles devem estar como o eco espera.

Fiz aqui do zero e funcionou corretamente sem erros.
- apague todos os conteineres
- apague todos os volumes. Pode rodar make apagar_volumes ou docker volume prune (isso é essencial se vc rodou antes sem os fontes estarem na posicao correta)
- posicione os fontes do sei na pasta default: ~/sei/FontesSEI
- se necessário apague o sei/config/ConfiguracaoSEI.php e sip/config/ConfiguracaoSip.php (deixe q o conteiner cuida desses arquivos)
- make setup
- make logs_app-atualizador para acompanhar a instalacao do SEI

Tenta ai e se n conseguir avisa q tento ajudar

**Comment by wll8090** [comment]
~/sei/FontesSEI   : esta ok     --> sei_v4.0.9
~/sei/certs            : esta ok

os arquivos que pediu para apagar encontram-se em:

sei-docker
    ├── containeres
    │   ├── app
    │   │   ├── Dockerfile
    │   │   └── files
    │   │       ├── conf
    │   │       │   ├── ConfiguracaoSEI.php     <<<
    │   │       │   ├── ConfiguracaoSip.php    <<<
    │   │       │   ├── sei.conf



tenho com o arvore:
~
├── certs
├── FontesSEI
│   ├── infra
│   │   ├── infra_css
│   │   ├── infra_js
│   │   └── infra_php
│   ├── sei
│   │   ├── bin
│   │   ├── scripts
│   │   └── web
│   ├── sei_v4.0.9.zip
│   └── sip
│       ├── scripts
│       └── web
└── sei-dockertree

**Comment by marlinhares** [comment]
Olá @wll8090 pode mandar a msg aqui para que outros users futuramente possam pesquisar, caso tenham problema similar. Vi q tu mandou resposta direto no email

**Comment by wll8090** [comment]
@marlinhares deu certo em localhost.
O meu erro era que estava sem a versão requerida 4.0.0 que contém a pasta /opt/sei/config/, vi que estava apenas com arquivos de atualização.

**Comment by rafaelfariasbsb** [comment]
Somente para complementar o amigo, já que passei pelo mesmo problema. Se vc começa o projeto com a versão 4.0.9 (que seria a última versão atual) ela não tem as pastas sei/config e sip/config. Não sei se seria a solução correta, mas basta criar a pastas na versão 4.0.9 que o projeto sobe sem problemas
