### ISSUE TITLE
Erro envio de email ao criar usuário externo

### ISSUE THREAD

**Issue by abreujean** [spbgovbr/sei-docker#55]
Olá @marlinhares 

Como eu configuro as variáveis do phpmailer no projeto?

no env está assim 

```
export APP_MAIL_TIPO=1 #1 = sendmail (neste caso nao eh necessario configurar os atributos abaixo), 2 = SMTP
export APP_MAIL_SERVIDOR=smtp.gmail.com
export APP_MAIL_PORTA=587
export APP_MAIL_CODIFICACAO=8bit #8bit, 7bit, binary, base64, quoted-printable
export APP_MAIL_MAXDESTINATARIOS=999 #numero maximo de destinatarios por mensagem
export APP_MAIL_MAXTAMANHOANEXOSMB=999 #tamanho maximo dos anexos em Mb por mensagem
export APP_MAIL_SEGURANCA=TLS #/TLS, SSL ou vazio
export APP_MAIL_AUTENTICAR=true # false se true entao informar Usuario e Senha
export APP_MAIL_USUARIO=******[meu email]
export APP_MAIL_SENHA=*****[minha senha]
export APP_MAIL_PROTEGIDO=

```

só que eu recebo o seguinte erro depois de tentar criar o usuário externo

![image](https://user-images.githubusercontent.com/30299701/231212396-1c5bf5b2-6bc9-483f-b84e-e50209888635.png)

pode me auxiliar nessa situação?

**Comment by marlinhares** [comment]
opa isso é um bug. No conteiner de app nao esta instalado sendmail
Enquanto nao liberamos pode usar o SMTP Tipo=2 ou entao entra no conteiner de app e roda

```
yum install -y sendmail
```

Tu tb vai ter q configurar o sendmail.
Apenas uma duvida pq vc usa o sendmail ao inves do smtp?

**Comment by abreujean** [comment]
@marlinhares  coloquei no Tipo = 2 
configurei meu email e senha para fazer um teste como está na imagem abaixo

![image](https://user-images.githubusercontent.com/30299701/232505894-bc5b482c-80b9-476a-b740-be1ff183e4c2.png)

Mais agora quando tento criar o usuário externo me retorna o erro de 
`
Falha na conexão com o servidor de e-mails.
`
subi o MailCatcher também para acompanhar os emails enviados

quando configuro o phpmailer em outras aplicações que temos em nossos servidores usamos a porta 587
e no host colocamos smtp.gmail.com
Isso tem alguma relação com essa configuração do SEI
ou eu deixo a porta 25 e o APP_MAIL_SERVIDOR como mail como está no envlocal.env ?

**Comment by marlinhares** [comment]
opa cara criei um do zero aqui e funfou perfeitamente o MAIL CATCHER.
A única alteracao no envlocal foi:

```
export MAIL_CATCHER_PRESENTE=true
```

Depois de enviar o email basta consulta-lo em: host/mailadmin, caso esteja usando o haproxy do projeto
![image](https://user-images.githubusercontent.com/16244217/233080750-e0f3e24f-a123-4893-8f5f-dfb6ec7599f3.png)

Inclusive aceita até enviar anexos.

**Comment by marlinhares** [comment]
Com relacao ao envio via smtp pelo gmail tb funfou fino.

No envlocal.env apenas alterei aqui:

```
export APP_MAIL_TIPO=2 #1 = sendmail (neste caso nao eh necessario configurar os atributos abaixo), 2 = SMTP
export APP_MAIL_SERVIDOR=smtp.gmail.com
export APP_MAIL_PORTA=587
export APP_MAIL_CODIFICACAO=8bit #8bit, 7bit, binary, base64, quoted-printable
export APP_MAIL_MAXDESTINATARIOS=999 #numero maximo de destinatarios por mensagem
export APP_MAIL_MAXTAMANHOANEXOSMB=999 #tamanho maximo dos anexos em Mb por mensagem
export APP_MAIL_SEGURANCA=TLS #/TLS, SSL ou vazio
export APP_MAIL_AUTENTICAR=true # false se true entao informar Usuario e Senha
export APP_MAIL_USUARIO=marlinhares@gmail.com
export APP_MAIL_SENHA=<<senha de aplicacao do google. n eh a do gmail>>
```

Enviou perfeitamente o email.
A unica observação é que seu gmail precisa estar habilitado com o smtp e senha para aplicativos externos.

**Comment by abreujean** [comment]
@marlinhares Mais uma vez obrigado!
o problema era a senha, eu estava colocando a do gmail,
depois de gerar a senha de aplicação do google funcionou.
