### ISSUE TITLE
Erro haproxy

### ISSUE THREAD

**Issue by abreujean** [spbgovbr/sei-docker#63]
![image](https://github.com/spbgovbr/sei-docker/assets/30299701/ea410b1a-7959-4391-afd7-ed437ca16dd4)

Quando tento levantar o projeto recebo o erro

`
ERROR:haproxy:Config check failed. NOT reloading haproxy: [WARNING] 243/040228 (46) : parsing [/haproxy.cfg:41] : a 'redirect' rule placed after a 'use_backend' rule will still be processed before.
`

Como na imagem acima, tentei alguma alterações no env e continuo com o mesmo problema.
Estou usando o SEI-Fontes-v4.1.0, Docker version 24.0.5 e docker Compose version v2.3.3
Pode me auxiliar em algo para resolver esse problema?

**Comment by rafaelcavalheri** [comment]
Aqui tive esse problema, era erro no certificado, foi necessario converter o server.key para RSA com o comando

openssl rsa -in server.key -out server_new.key -traditional

Após isso, concatenar este novo cert.key com o cert.crt e criar um cert0.pem

executar o comando make criar_volume_certs e make run

mesmo após esses passos o certificado cert0.pem nao foi copiado para a pasta certs do haproxy

então foi copiado manualmente para dentro do docker

**Comment by marlinhares** [comment]
@abreujean to achando que vc está com o problema descrito na issue #64 

Verifique se é esse o problema. Ai no final da issue tem a solução.

**Comment by abreujean** [comment]
Esse erro está resolvido, era a versão do docker-compose.
