### ISSUE TITLE
erro em : 'Federacao' => array(           'Habilitado' => false          ),

### ISSUE THREAD

**Issue by wll8090** [spbgovbr/sei-docker#66]
ainda va versão enterior no docker.
modificando o arquivo  "ConfiguracaoSEI.php"

em:        
'Federacao' => array(
          'Habilitado' => true
         ),

realizando os passos de :
apagar a imagem do app
apagar o volume de arquivos externos
make build_docker_compose
make setup

não modifica para true dentro do container...
continua em false....

**Comment by marlinhares** [comment]
hum isso daqui ainda n testei, mas é possível que esteja acontecendo sim.
O arquivo ConfiguracaoSEI e Sip são montados em tempo de execução. Qd o conteiner sobe.

Nesta versão sempre q subir o conteiner, vc terá que alterar manualmente essa variável.

Vamos lançar uma nova versão onde essa variável Habilitado esteja no envlocal.env.

**Comment by wll8090** [comment]
em relação ser manualmente, seria dentro do container ou em outro arquivo especifico que monte ele??

**Comment by marlinhares** [comment]
> em relação ser manualmente, seria dentro do container ou em outro arquivo especifico que monte ele??

depois q o conteiner subir, basta entrar no arquivo e alterar.
caso tenha vários apps vai ter q entrar em todos e alterar.
sempre q o conteiner for restartado tb tem q alterar.

Isso até liberarmos a nova versão. Ai vai alterar automaticamente.

**Comment by marlinhares** [comment]
Ajuste disponível na release https://github.com/spbgovbr/sei-docker/releases/tag/2.1.1

Duvidas basta perguntar
