### ISSUE TITLE
Problemas como httpd

### ISSUE THREAD

**Issue by tpklge** [spbgovbr/sei-docker#68]
Tentanto subir a aplicação em uma ec2 vazia, segui os 4 passos, o  make up roda lisinho, mas ao final o httpd não sobe, ou fica tentando subir sem as portas publicadas. Não alterei nada nos arquivos. Eu estava tentando subir em uma outra ec2 que já rodo umas aplicações no docker (usando portainer) e achei que tivesse alguma coisa impedindo. Criei uma ec2 debian11 nova e instalei o que precisava, sem sucesso. 
No log do container:
root@ip-172-31-0-185:/home/admin/sei-docker/dev# docker httpd logs
docker: 'httpd' is not a docker command.
See 'docker --help'
root@ip-172-31-0-185:/home/admin/sei-docker/dev# docker container logs httpd
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(

Fatal error: Uncaught Falha ao abrir conex�o com o banco de dados.
  thrown in /opt/infra/infra_php/InfraMySqli.php on line 983
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHP Fatal error:  Uncaught Falha ao abrir conex�o com o banco de dados.
  thrown in /opt/infra/infra_php/InfraMySqli.php on line 983
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHP Fatal error:  Uncaught Error: Call to undefined method BancoSip::setBolScript() in Command line code:8
Stack trace:
#0 {main}
  thrown in Command line code on line 8

**Comment by tpklge** [comment]
Depois de desistir do teste em modo dev, resolvi ir para o modo infra. Após um final de semana "brincando" com o sistema, hoje pela manhã, mesmo após restart dos contêineres , a aplicação dá erro 503 (mas o log do balanceador e do httpd estão normais).

**Comment by marlinhares** [comment]
Olá @tpklge subi agora uma versão do zero usando a pasta infra e subiu td ok.
Bastou:
- fazer o clone do projeto.
- posicionar o fonte do SEI em ~/sei/FonteSEI/
- cd infra
- make setup
- make logs
- aguarda a instalacao e depois basta acessar https://localhost/sei

Verifica se essa issue aqui te atinge: #72

**Comment by marlinhares** [comment]
Fechando. Se precisar de ajuda avisar
