### ISSUE TITLE
Erro Intalação do SEI - ERROR: for app-atualizador

### ISSUE THREAD

**Issue by rafaelssrrramos** [spbgovbr/sei-docker#78]
Estou enfrentando o seguinte erro na instalação do SEI 4.1.0, 

Estou executando o comando "make setup" e também o "make run", 

O arquivo executado "makefile" encontra-se na pasta sei-docker/infra, 

Caso deseje que eles aparecam ative no envlocal.env o modo Debug
make[1]: Leaving directory '/home/administrador/projetos/git/github/spbgovbr/sei-docker/infra'
docker-compose -f orquestrators/docker-compose/docker-compose.yml  up -d --remove-orphans
Creating network "docker-compose_default" with the default driver
Creating docker-compose_storage-openldap_1 ... done
Creating docker-compose_storage-app_1      ... done
Creating docker-compose_storage-certs_1    ... done
Creating docker-compose_solr_1             ... done
Creating docker-compose_jod_1              ... done
Creating docker-compose_memcached_1        ... done
Creating docker-compose_db_1               ... done
Creating docker-compose_app-agendador_1    ...
Creating docker-compose_app_1              ...
Creating docker-compose_app-atualizador_1  ... error

--------------------------------------------------------------------------------------

ERROR: for app-atualizador  Cannot start service app-atualizador: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/marcelo/projetos/github/spbgovbr/sei-docker/containers/app/app-ci/assets/scripts-e-automatizadores/entrypoint-atualizador.sh" to rootfs at "/entrypoint-atualizador.sh": mount /home/marcelo/projetos/github/spbgovbr/sei-docker/containers/app/app-ci/assets/scripts-e-automatizadores/entrypoint-atualizador.sh:/entrypoint-atualizador.sh (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:331: run] Error 1

----------------------------------------------------------------------------
Quando acesso a log 

app-agendador_1     | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app-agendador_1     | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos

**Comment by Larvin-Vinicius** [comment]
Aqui deu o mesmo problema em uma instancia de testes.
* Parei os containers(Repositório antigo). 
* rodei o comando ```make clear```
* Fiz o clone do repositório atualizado
* Ao iniciar novamente os containers retornou esse erro.

**Comment by rafaelssrrramos** [comment]
Olá, 
Fiz uma alteração no aquivo docker-compose-template.yml, no "infra/orquestrators/docker-compose/docker-compose-template.yml" apontando para o meu diretorio home, dessa forma o erro "Criando docker-compose_app-atualizador_1 ... erro" não aconteceu. 

Falha aparentimente estava na linha 133

            - /home/marcelo/projetos/github/spbgovbr/sei-docker/containers/app/app-ci/assets/scripts-e-automatizadores/entrypoint-atualizador.sh:/entrypoint-atualizador.sh

Mas o erro de não subi a aplicação continua, apresentando a log abaixo.

Alguem poderia me ajudar?

app-agendador_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
app_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
app_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
app_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
app_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
app-agendador_1 | Aguardando conteúdo atualizado instalar e atualizar o SEI e módulos
![image](https://github.com/spbgovbr/sei-docker/assets/122367279/41d1726b-ba89-42a7-8f3d-d60770095e3b)

app_1 | Aguardando conteúdo atualizado, instalar e atualizar o SEI e módulos

![App](https://github.com/spbgovbr/sei-docker/assets/122367279/2820c508-94d4-4080-80e2-df3cda2656c4)

**Comment by marlinhares** [comment]
Pessoal ha realmente uma falha. A culpa foii minha que esqueci uma diretiva no docker-compose-template.yml que alterei para testar e esqueci de voltar

Ja to ajustando

**Comment by marlinhares** [comment]
Acabei de fazer o commit. Por favor tentar novamente.
Para limpar os dados da instancia rodar o:
make clear
make apagar_volumes

Cuidado pois o make apagar_volumes vai destruir os dados do projeto inclusive banco pra criar novamente

**Comment by marlinhares** [comment]
Nao esquecer de baixar o projeto novamente ou rodar o git pull

**Comment by rafaelssrrramos** [comment]
Olá, 

Pelo apoio!

Consegui subi a aplicação, porem apresentando o erro de "Falha na conexão com Sistema de Permissões" enos logs também "
app-agendador_1     | PHP Fatal error:  Uncaught Falha na conex�o com o servidor de e-mails.
app-agendador_1     |   thrown in /opt/infra/infra_php/InfraMail.php on line 327

Não sei se o erro acima impactaria.

Utilizei o usuario "teste" com a senha "teste"

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/f7beda8a-97f4-465d-8b22-ed34e1c7c5e4)

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/192ec40c-b1ba-4840-91da-aa89ffb12fd2)

obs: estou utilizando uma VM no Azure para subida da aplicação

https://172.172.124.203/

Com o procedimento e um no git clone, voltou apresenta o erro "Aguardando conteiner atualizador instalar e atualizar o SEI e modulos"

**Comment by rafaelssrrramos** [comment]
> Não esqueça de baixar o projeto novo ou rodar o git pull

Vou proceder dessa foram, ainda não tinha feito, utilizei os comandos com a alteração que realizei no docker-compose-template.yml

**Comment by rafaelssrrramos** [comment]
Olá, 

Fiz o processo de clone do diretorio novamente, e realizei procedimento com o comando "make setup" e agora está aprsentando o erro abaixo, consegue me ajudar?


app-agendador_1     | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app-agendador_1     | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos
app_1               | Aguardando conteiner atualizador instalar e atualizar o SEI e modulos

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/60a77d46-6a5a-40e8-90bf-49d6e4a4c274)

**Comment by marlinhares** [comment]
opa deixa eu tentar ajudar

essa mensagem ai nao é erro. Ela diz q está esperando o atualizador instalar o sei e os modulos pra vc

verifique os logs do atualizador com:
make logs_app-atualizador

rode tb um docker ps e coloque aqui

**Comment by rafaelssrrramos** [comment]
Olá, segue abaixo o resultado dos comandos.

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/129ac619-5896-4806-81f7-03f6e548b1b0)

Imagem configuração do envlocal.env

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/297ecf24-76d6-4d8d-b4f4-74673461115f)

segue abaixo o diretorio e as permissões.
obs: rodei o make setup com "sudo", não sei se estou fazendo algum procedimento errado.

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/f08f301c-5103-45ec-a67c-e7852980bfd0)

**Comment by marlinhares** [comment]
ai no log do atualizador ele falou o erro: Codigo fonte do sei nao encontrado

qual o resultado do comando:
ls -lha /home/administrador/sei/FonteSEI

?

**Comment by rafaelssrrramos** [comment]
Segue abaixo o resultado:

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/d8be3fef-6621-42fa-b7c7-23eae5d12bac)

**Comment by marlinhares** [comment]
perfeito estamos chegando no erro. 
Veja q essa pasta ta vazia. O makefile vai pegar o conteudo dela criar um volume fontes e o ecossistema vai usar esse fonte

Se ela esta vazia entao nao vai subir. Agora eu vi q tu tem duas pastas fontes, talvez isso esteja te confundindo.
- apague essa pasta FonteSEI
- renomeie essa pasta FontesSEI para FonteSEI

Verifique se as pastas infra, sei e sip estao nela e obviamente elas estejam com o fonte do SEI.

Vamos um pouco além e vamos dar uma limpada geral tb pois n sei o q vc alterou:
- vamos parar td
- docker stop $(docker ps -aq)
- docker rm $(docker ps -aq)
- vamos apagar os conteineres
- docker system prune -a
- vamos apagar os volumes (atencao vai apagar ttds os volumes, faca backup caso tenha algo importante)
- docker volume prune
- remove os arquivos de config do sei e sip caso essa pasta esteja suja
- rm /home/administrador/sei/FonteSEI/sei/config/ConfiguracaoSEI.php
- rm /home/administrador/sei/FonteSEI/sip/config/ConfiguracaoSip.php
- apagar o sei-docker
- rm -rf sei-docker
- faz o clone 
- git clone https://github.com/spbgovbr/sei-docker
-  cd sei-docker/infra
-  make setup
-  make logs_app-atualizador

apenas cuidado com os dirs pois n os informei completamente

dessa forma vai subir default
n se preocupe ainda em acessar o sistema isso sera o prox passo

coloque o resultado aqui

**Comment by marlinhares** [comment]
vou sair um pouco mas volto em 15mins

**Comment by marlinhares** [comment]
e ai como está? Conseguiu?

**Comment by rafaelssrrramos** [comment]
Estou fazendo o precedimento nesse momento, já informo as saídas

**Comment by rafaelssrrramos** [comment]
O sistema ainda não carregou!

Segue abaixo o log do make logs_app-atualizador

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/4f365b55-90be-418b-a5ad-db7dbc5e6929)

No "make logs"

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/47264f18-dbe3-41e2-a868-53b49f498707)

![image](https://github.com/spbgovbr/sei-docker/assets/122367279/71838775-787d-477c-b297-46737cfd316b)

**Comment by marlinhares** [comment]
Ótimo agora ta funcionando o instalador. Veja ai q o make logs_app-atualizador instalou e liberou para o servidor de aplicacao.
Agora vamos ver se a aplicacao subiu no localhost da vm

make logs_app (mande foto do final do log)

curl -Lkv localhost (mande foto do inicio e final do output de saída depois de rodar)

Se td certo o proximo passo vamos habilitar pra vc acessar o sei da sua casa/trabalho

**Comment by rafaelssrrramos** [comment]
Olá, segue abaixo

make logs_app
![image](https://github.com/spbgovbr/sei-docker/assets/122367279/e41c4d88-507d-46e7-9adb-34ebc914c778)

curl -Lkv localhost
Inicio (Imagem inicio do log)
![image](https://github.com/spbgovbr/sei-docker/assets/122367279/c7226b5f-2a5b-4d42-8de9-973fd0c594c1)

Fim (Imagem final do log)
![image](https://github.com/spbgovbr/sei-docker/assets/122367279/ef8b4070-0e4f-4bea-a675-efbc27b7fd9e)

**Comment by marlinhares** [comment]
Pronto acho q esta td em ordem. Veja ai no log do app que ele liberou o apache para uso e vc conseguiu abrir a pagina inicial do sei no seu localhost.
Agora vamos destruir o sei pra subir na sua url:

Para destruir:
- make clear
- make apagar_volumes

Altere o arquivo envlocal.env e procure a var:

APP_HOST=localhost e altere para sua url, por ex:

APP_HOST=meusei.org.br

Caso nao tenha uma url registrada na internet pode inventar uma, mas nesse caso, para acessar vc terá q adicionar ao /etc/hosts da sua maquina em casa ou trabalho o caminho para essa url inventada.

Depois de alterado o APP_HOST pode subir novamente:
make setup
make logs_app-atualizador, qd o atualizador finalizar rode
make logs_app

Quando o apache tiver liberado pode acessar o SEI

**Comment by rafaelssrrramos** [comment]
@marlinhares , Muito obrigado pelo apoio!

O sistema SEI disponibilizado com sucesso!

No momento de colocar em ambiente de produção, você teria alguma recomendação?

Para o certificado SSL valido, vc teria alguma dica?

Muito obrigado por sua presteza e apoio.

**Comment by marlinhares** [comment]
Q bom q conseguiu.

Cara tem q ler a documentacao desse projeto. Tem os videos tb q vao dar uma orientada geral.
Agora esse projeto aqui n é recomendado para producao ok.
Para producao vc terá q se preocupar com diversos pontos de seguranca e performance que nao estao descritos aqui nesse projeto.

Nós temos a intenção de lançar uma versão de produção mas esse trabalho ainda não foi priorizado pela chefia.

Com relação ao cert válido da uma olhada na issue #53

**Comment by rafaelssrrramos** [comment]
Obrigado pelo retorno.

Seria otimo essa versão para produção.

Na documentação, para o ambiente em produção, informa sobre a infra tradicional.

Videos de apoio e orientações eu consegui encontrar o seus, que são excelentes, teria outros? Ou saberia orientar onde conseguiria?

Muito Obrigado!

**Comment by marlinhares** [comment]
@higodf PSC
Necessidade de receita de produção para ser priorizada caso achem necessário
