### ISSUE TITLE
Migração para SEI DOCKER

### ISSUE THREAD

**Issue by eemarwell** [spbgovbr/sei-docker#85]
Olá, tudo bem?

Gostaria de, se possível, receber algum auxílio referente a uma possibilidade de migração, trabalho na Defensoria Pública e aqui utilizamos o SEI na versão 4.7, peguei o sistema em andamento e hoje temos a necessidade de utilizar o Solr (a maior demanda no momento), achei o repositório sei-docker pesquisando por esta integração e até onde vi neste repositório temos o Solr implantado, gostaria de saber se consigo por exemplo utilizar esta versão do Solr 9.4 e encaixar para funcionar com o SEI 4.7 que temos. Vi que já existe a versão 5.0 do SEI, não sei ao certo quais as melhorias de fato, mas não temos aqui mais desenvolvedores da época em que o SEI foi implantado, então não consigo informações sobre como o código do SEI foi obtido.

Agradeço o apoio e a disponibilização deste projeto!

**Comment by eemarwell** [comment]
Uma outra dúvida, baixei o projeto e estou rodando apenas o solr 9.4 para fim de testes e ele já vem com um security configurado, trazendo uma autenticação a tela de dashboard, em algum lugar está documentada a senha padrão? Tentei gerar outra pelo processo citado na documentação oficial do Solr, rebuildei a imagem e subi novamente, mas não está funcionando.

![image](https://github.com/spbgovbr/sei-docker/assets/9139221/6a73e475-e51c-4a6c-8edd-8fc8120a6fd1)

**Comment by caduvieira** [comment]
> Gostaria de, se possível, receber algum auxílio referente a uma possibilidade de migração, trabalho na Defensoria Pública e aqui utilizamos o SEI na versão 4.7, peguei o sistema em andamento e hoje temos a necessidade de utilizar o Solr (a maior demanda no momento), achei o repositório sei-docker pesquisando por esta integração e até onde vi neste repositório temos o Solr implantado, gostaria de saber se consigo por exemplo utilizar esta versão do Solr 9.4 e encaixar para funcionar com o SEI 4.7 que temos. Vi que já existe a versão 5.0 do SEI, não sei ao certo quais as melhorias de fato, mas não temos aqui mais desenvolvedores da época em que o SEI foi implantado, então não consigo informações sobre como o código do SEI foi obtido.

Não existe distribuição do MGI nem do TRF4 de SEI 4.7.

Esse repositório aqui não tem uma disponibilização para produção.

**Comment by eemarwell** [comment]
> > Gostaria de, se possível, receber algum auxílio referente a uma possibilidade de migração, trabalho na Defensoria Pública e aqui utilizamos o SEI na versão 4.7, peguei o sistema em andamento e hoje temos a necessidade de utilizar o Solr (a maior demanda no momento), achei o repositório sei-docker pesquisando por esta integração e até onde vi neste repositório temos o Solr implantado, gostaria de saber se consigo por exemplo utilizar esta versão do Solr 9.4 e encaixar para funcionar com o SEI 4.7 que temos. Vi que já existe a versão 5.0 do SEI, não sei ao certo quais as melhorias de fato, mas não temos aqui mais desenvolvedores da época em que o SEI foi implantado, então não consigo informações sobre como o código do SEI foi obtido.
> 
> Não existe distribuição do MGI nem do TRF4 de SEI 4.7.
> 
> Esse repositório aqui não tem uma disponibilização para produção.

Verdade, mencionei a versão de forma errada, essas são as versões:

![image](https://github.com/spbgovbr/sei-docker/assets/9139221/b46d7cb3-1738-442e-9029-46bb48679dfd)

Na verdade precisava mais de um possível auxílio com o Solr, que não estamos tendo êxito em implementar. Mas estamos andando com a versão 8.2 do Solr junto ao SEI 4.0.7.

**Comment by caduvieira** [comment]
O SEI 4.0.X está homologado para uma versão específica do solr. Verifique a documentação que o TRF4 deu para vocês. O SEI não usa nenhuma biblioteca profissional pra acessar/comunicar com o solr. Por esse motivo usar qualquer outra versão deve dar problema.

O solr na documentação que tenho acesso é o 8.2.0 https://github.com/pengovbr/sei/blob/main/docs/INSTALACAO.md

**Comment by caduvieira** [comment]
Se você tem acesso ao código do SEI do TRF4 você deve ter um ACT com o TRF4

**Comment by eemarwell** [comment]
> O SEI 4.0.X está homologado para uma versão específica do solr. Verifique a documentação que o TRF4 deu para vocês. O SEI não usa nenhuma biblioteca profissional pra acessar/comunicar com o solr. Por esse motivo usar qualquer outra versão deve dar problema.
> 
> O solr na documentação que tenho acesso é o 8.2.0 https://github.com/pengovbr/sei/blob/main/docs/INSTALACAO.md

Entendi, no repositório que tenho está rodando o SEI 4.0.7 e estava já dentro do diretório o solr_8.2.0, é com o que estou trabalhando no momento.
Mas nem acesso a esse doc de INSTALACAO.md eu tenho.



> Se você tem acesso ao código do SEI do TRF4 você deve ter um ACT com o TRF4

Provavelmente tenha, infelizmente foi mudada a gestão e os desenvolvedores, não tenho pra quem perguntar, provavelmente terei que escalar isso pra administração superior, mas agradeço a ajuda.

**Comment by marlinhares** [comment]
@eemarwell permitam-me complementar algumas infos
se vc posicionar o fonte do SEI no local correto
default é: ~/sei/FonteSEI

rodar:
make setup

depois
make logs

vc vai poder acompanhar os logs ate ficar td pronto
Depois basta acessar https://localhost (ou a url q vc definiu no env) e usar o sei
o Solr para o sei4 é o 8.2 e vai ter disponível um conteiner ai rodando do solr depois do make setup

para acessar, se tudo certo, basta digitar https://localhost/solr e vai entrar na pagina de administracao do solr.
Para o solr8 não tem usuário, acesso é livre.
Para o solr9 a senha fica é:  admin / SolrAdmin123$, mas o solr9 como dito pelo Cadu acima apenas para o sei5

Se tiver duvidas para subir pode abrir issue q tentaremos ajudar. Porem n garatimos velocidade na resposta pois temos outras demandas

**Comment by marlinhares** [comment]
se quiser subir o sei5, no default, basta depois de posicionar o fonte rodar:

cat envlocal-example-mysql-sei5.env >> envlocal.env

para ajustar o envlocal para o sei5 e vai subir td fino

**Comment by eemarwell** [comment]
Opa, obrigado pela resposta @marlinhares! Tinha até desistido nesse momento, por não ter acesso às atualizações, nossa gestora esteve no Condege e teve até apresentação do SEI com IA lá, infelizmente nem atualização e acesso ao SEI 5 temos no momento. Mas assim que ela retornar, irei atrás de como obter essa autorização e esse acesso pra gente conseguir atualizar. Consegui pôr o Solr 8.2 pra funcionar, indexar os arquivos, habilitei segurança com o plugin de auth basic, mas está gerando vários erros na tela de pesquisa, erros de formatação xml, erros de datas inválidas... talvez essa atualização ajude a ter essa funcionalidade do Solr com mais facilidade.
