### ISSUE TITLE
(100000002): Erro cadastrando registro em infra_auditoria.

### ISSUE THREAD

**Issue by jhspjr** [spbgovbr/sei-docker#94]
Caros, alguém sabe o motivo dessa mensagem?
os dados não gravam no BD

**Comment by marlinhares** [comment]
Olá @jhspjr vc está usando um banco customizado? Ou o banco de dados fornecido aqui nesse projeto?
Pode ser vários motivos para não estar gravando os dados. Permissão seria um dos primeiros pontos a se verificar.
Como que aparece o erro printado na tela e tb no log do apache?

**Comment by jhspjr** [comment]
Obrigado, pela ajuda @marlinhares. Era configuração de BD. (problema no encoding)
