### ISSUE TITLE
usando SEI com nginx

### ISSUE THREAD

**Issue by rafaelfariasbsb** [spbgovbr/sei-docker#95]
Primeiro gostaria de pedir desculpa por colocar esse tópico aqui, mas estou precisando de ajuda em configurar o SEI no nginx preciso  fazer alguns testes, caso alguem tem alguma configuração por favor poderia compartilhar?

Obrigado pela ajuda

**Comment by marlinhares** [comment]
Olá @rafaelfariasbsb pode perguntar q se alguém souber vai responder.

Com relação ao nginx, esse projeto aqui oferece a receita kubernetes.
Nela tem o ingress que a época da criaçao do projeto o default do kube era um nginx. O nginx nele funciona com https, balanceador com apontamento dinamico para a quantidade de nós de aplicação desejada e persistencia da sessao via cookies.

ATENÇÃO. A CONFIGURACAO GERADA NESSE NGINX SERVE APENAS PARA AMBIENTE DE DEV. PARA PRD VC DEVERA ADICIONAR DIVERSAS OUTRAS DIRETIVAS.
Até esta data não temos uma previsão de quando iremos liberar um projeto pronto para produção.

Depois de subir o sei no kubernetes, basta acessar o seu cluster e procurar o(s) conteiner(es) de nginx que a configuração vai estar la dentro.

Para gerar a receita kubernetes desse projeto basta:
- acessar a pasta infra
- alterar o seu envlocal.env com os parametros corretos (para o nginx é obrigatorio informar a url correta)
- rodar:
```
make kubernetes_montar_yaml
```
- seguir a orientação do comando

**Comment by caduvieira** [comment]
> Com relação ao nginx, esse projeto aqui oferece a receita kubernetes.
Nela tem o ingress que a época da criaçao do projeto o default do kube era um nginx. O nginx nele funciona com https, balanceador com apontamento dinamico para a quantidade de nós de aplicação desejada e persistencia da sessao via cookies.

Estava pensando que ele perguntou como servidor para o PHP. 

> configurar o SEI no nginx

Qual a função o nginx estaria exercendo?

**Comment by rafaelfariasbsb** [comment]
sim seria como servidor das páginas substituindo o apache.

**Comment by rafaelfariasbsb** [comment]
Fiz alguns testes e conseguir rodar, segue a configuração que fiz. Lembrando que são somente teste e não siginfica que e a configuração mais otimizada e não deve ser usada em produção

server{

        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        #server_name teste;
        ssl_certificate /etc/nginx/certificate/sei_chained.crt;
        ssl_certificate_key /etc/nginx/certificate/sei.key;
        location /sei {
            alias /opt/sei/web;
            index index.php;
            location ~ \.php$ {
                        try_files $uri =404;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
                        fastcgi_index index.php;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $request_filename;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
            }
        }
        location /sip {
            alias /opt/sip/web;
            index index.php;
            location ~ \.php$ {
                        try_files $uri =404;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
                        fastcgi_index index.php;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $request_filename;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
            }
        }
        location /infra_css {
                alias /opt/infra/infra_css;
        }
        location /infra_js  {
                alias /opt/infra/infra_js;
        }

}

**Comment by caduvieira** [comment]
Obrigado pelo exemplo
