### ISSUE TITLE
Erro SMTP no envio de email subindo SEI pelas as configurações de infra

### ISSUE THREAD

**Issue by brena-pmgv** [spbgovbr/sei-docker#98]
Ao subir o SEI seguindo as orientações da pasta `dev` conseguimos enviar email normalmente após setar os valores no arquivo `ConfiguracaoSEI.php`. Porém quando subimos o SEI utilizando as orientações da pasta `infra` recebemos este erro. As configurações foram setadas no `envlocal.env`.

Faz-se necessária alguma configuração diferente para utilizar ou habilitar o envio de emails ao subir o SEI pelo `Makefile` da pasta `infra`?

Obrigada.

**Erro:**
`Validação: PHPMAILER\PHPMAILER\EXCEPTION: SMTP ERROR: COULD NOT CONNECT TO SMTP HOST.`

![erro-smtp-sei](https://github.com/user-attachments/assets/702b3e83-b12d-4ce1-b03a-5108137ed7de)

**Comment by marlinhares** [comment]
Olá @brena-pmgv , verifique, antes de subir a aplicacao (com make setup) os valores no envlocal.env.
Tem várias entradas lá de MAIL. O ConfiguracaoSEI.php vai usar esses valores.

Testei agora um ambiente no kubernetes e bastou preencher a variavel:
APP_MAIL_SERVIDOR=relay.nuvem.gov.br
(no meu caso, esse relay ai aceita envio sem autenticacao e na porta 25, entao nao precisei preencher outras variaveis. Mas esse relay ai so funciona aqui pra gente. Ai local vc deve usar o seu do orgao.) 

----

Opcionalmente há a opcao de vc subir um ambiente local com um servidor de email para teste. Basta preencher a var
export MAIL_CATCHER_PRESENTE=true
e deixe as outras vars de email default sem alterar.
Depois para acessar o email basta usar: https://seuhost//mailadmin (caso esteja default, seria https://localhost/mailadmin)


----

Por fim olhando a sua figura de erro, ta informando ai que ele tentou conectar no servidor SMTP mas nao conseguiu.
Verifique se vc tem rota e permissao la no servidor q vc informou. O nó de aplicacao e agendamento do SEI tem que ter permissao para conectar nele.


Duvidas avisa

**Comment by brena-pmgv** [comment]
Obrigada pelo retorno, @marlinhares.

Com sua resposta pude perceber qual era o problema, estava colocando os valores das variáveis (`APP_MAIL_SERVIDOR`, `APP_MAIL_USUARIO` e `APP_MAIL_SENHA`) entre aspas.
